package com.assessment.fundtransfer.exception;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    INVALID_REQUEST,
    MALFORMED_JSON,
    MISSING_REQUEST_HEADER,
    MISSING_REQUEST_PARAMETER,
    TYPE_MISMATCH,
    METHOD_NOT_ALLOWED,
    ROUTE_NOT_FOUND,
    DUPLICATE_ACCOUNT,
    DUPLICATE_TRANSACTION_REFERENCE,
    ACCOUNT_NOT_FOUND,
    INSUFFICIENT_FUNDS,
    MISSING_IDEMPOTENCY_KEY,
    IDEMPOTENCY_KEY_CONFLICT,
    DUPLICATE_TRANSFER_REFERENCE,
    LOCK_CONFLICT,
    DATA_CONFLICT,
    INTERNAL_SERVER_ERROR
}
